name: Deploy para AWS com Serverless

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você queira que dispare o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Passo: Pega o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v2

      # 2. Passo: Instalar o Node.js para rodar o Serverless
      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Especifica a versão do Node.js

      # 3. Passo: Instalar as dependências do projeto
      - name: Instalar dependências
        run: npm install

      # 4. Passo: Rodar o comando para fazer o deploy na AWS
      - name: Deploy para AWS
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Região onde seu serviço será hospedado (mude se necessário)
